line.bot:
  channel-token: 'zXgotfgBHfTY1POvP6IUOEGRGqTu/PGn4UiAQmXC+pwDcZihPnDQ4KbqayGS99Dqfw+IQxcTSGorT7IWUpWkfkVRZr+JVHGYAKAXVcYzRllcBMwdT9CprpcdzAhh5dAzWskWTm/mqiCasT1vq1yjfQdB04t89/1O/w1cDnyilFU='
  channel-secret: '153127263bbe9cf36dda720c57ca5b27'
  handler.path: /callback